version: '2'

services:
  sqlserver:
    image: microsoft/mssql-server-linux
    ports:
      - 1433
    volumes:
      - /opt/mssql/data:/opt/mssql/data
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P@ssword1

  api:
    image: todobackend-api
    build:
      context: .
    environment:
      - SERVICE_NAME=api
      - ASPNETCORE_ENVIRONMENT=docker
    ports:
      - 5000
    links:
      - sqlserver

  loadbalancer:
    image: nginx
    build:
      context: ./nginx
    depends_on:
      - api
    ports:
      - "8080:80"

  consul:
    image: consul
    ports:
      - "8300:8300"
      - "8400:8400"
      - "8500:8500"
      - "8600:53/udp"

  registrator:
    image: gliderlabs/registrator
    depends_on:
      - consul
    command: -internal -resync 600 consul://consul:8500
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock"
